name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install pve-eslint
      run: |
        curl -sSfL http://download.proxmox.com/debian/devel/dists/bullseye/main/binary-amd64/pve-eslint_8.4.0-3_all.deb -o pve-eslint_8.4.0-3_all.deb
        sudo -E apt install -y ./pve-eslint_8.4.0-3_all.deb
        dpkg -l node-colors
        dpkg -L node-colors
        ls -l /usr/share/nodejs
        ls -l /usr/share/nodejs/colors
        cat /usr/share/nodejs/colors/package.json
        env
        sudo ln -s /usr/share/nodejs /usr/share/nodejs/node_modules
        sudo -E apt install -y strace
        strace eslint
